[package]
name = "vexillologist"
version = "1.4.0"
edition = "2021"
publish = false
repository = "https://github.com/maddiemort/vexillologist"

[package.metadata.dist]
dist = true

[dependencies]
anyhow = "1.0.66"
chrono = "0.4.38"
dotenvy = "0.15.7"
indoc = "2.0.5"
metrics = "0.24.2"
metrics-exporter-prometheus = "0.17.2"
tap = "1.0.1"
thiserror = "1.0.61"
tracing = "0.1.40"
tracing-loki = "=0.2.5"
url = "2.5.4"

[dependencies.serenity]
version = "0.12.0"
default-features = false
features = ["client", "gateway", "rustls_backend", "model"]

[dependencies.sqlx]
version = "0.7.4"
features = ["chrono", "postgres", "runtime-tokio"]

[dependencies.tokio]
version = "1.40.0"
features = ["full"]

[dependencies.tracing-subscriber]
version = "0.3.18"
features = ["fmt", "env-filter"]

[patch.crates-io]
tracing-loki = { git = "https://github.com/gabrik/tracing-loki", branch = "fix/ram-usage" }

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
