[package]
name = "vexillologist"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.66"
indoc = "2.0.5"
shuttle-runtime = "0.46.0"
shuttle-serenity = "0.46.0"
tap = "1.0.1"
thiserror = "1.0.61"
tracing = "0.1.40"

[dependencies.serenity]
version = "0.12.0"
default-features = false
features = ["client", "gateway", "rustls_backend", "model"]

[dependencies.shuttle-shared-db]
version = "0.46.0"
features = ["postgres", "sqlx"]

[dependencies.sqlx]
version = "0.7.4"
features = ["chrono"]
